
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Mar  7 2020 16:40:48 EST (Mar  7 2020 21:40:48 UTC)

// Verification Directory fv/LUT_WINPUT4 

module LUT_WINPUT4(in, out, key);
  input [3:0] in;
  input [15:0] key;
  output out;
  wire [3:0] in;
  wire [15:0] key;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58;
  nand g389__7837 (out, n_57, n_58);
  nand g390__7557 (n_58, in[3], n_56);
  nand g391__7654 (n_57, n_0, n_55);
  nand g392__8867 (n_56, n_46, n_54);
  nand g393__1377 (n_55, n_52, n_53);
  nor g394__3717 (n_54, n_48, n_51);
  nor g395__4599 (n_53, n_38, n_49);
  not g396 (n_52, n_50);
  not g397 (n_51, n_47);
  nand g398__3779 (n_50, n_30, n_44);
  nand g403__2007 (n_49, n_31, n_42);
  nand g405__1237 (n_48, n_29, n_41);
  nand g399__1297 (n_47, n_43, n_40);
  not g400 (n_46, n_45);
  nand g402__2006 (n_45, n_34, n_37);
  nand g401__2833 (n_44, n_43, n_39);
  nand g414__7547 (n_42, in[1], n_32);
  nand g415__7765 (n_41, in[1], n_36);
  nand g404__9867 (n_40, n_18, n_26);
  not g406 (n_39, n_27);
  not g412 (n_38, n_35);
  nand g413__3377 (n_37, in[2], n_24);
  not g418 (n_36, n_23);
  nand g417__9719 (n_35, key[4], n_33);
  nand g416__1591 (n_34, key[12], n_33);
  not g420 (n_32, n_22);
  nand g409__6789 (n_31, n_28, n_15);
  nand g408__5927 (n_30, n_19, n_17);
  nand g407__2001 (n_29, n_28, n_16);
  nand g410__1122 (n_27, n_25, n_14);
  nand g411__2005 (n_26, n_25, n_13);
  not g419 (n_24, n_20);
  nand g421__9771 (n_23, key[14], n_21);
  nand g424__3457 (n_22, key[6], n_21);
  nand g423__1279 (n_20, key[13], n_19);
  nand g422__6179 (n_18, key[9], n_19);
  nand g426__7837 (n_17, n_3, n_10);
  nor g425__7557 (n_33, in[1], n_12);
  nand g429__7654 (n_16, n_4, n_7);
  nand g428__8867 (n_15, n_2, n_8);
  nand g427__1377 (n_14, n_1, n_11);
  nand g430__3717 (n_13, n_5, n_6);
  not g437 (n_21, n_12);
  nand g431__4599 (n_11, key[0], n_9);
  nand g432__3779 (n_10, key[1], n_43);
  nor g443__2007 (n_28, n_25, n_9);
  nand g444__1237 (n_12, in[2], n_25);
  nand g435__1297 (n_8, key[3], n_43);
  nand g434__2006 (n_7, key[11], n_43);
  nand g433__2833 (n_6, key[8], n_9);
  nor g436__7547 (n_19, in[1], n_25);
  nand g438__7765 (n_5, key[10], in[1]);
  nand g439__9867 (n_4, key[15], in[2]);
  nand g440__3377 (n_3, key[5], in[2]);
  nand g441__9719 (n_2, key[7], in[2]);
  nand g442__1591 (n_1, key[2], in[1]);
  not g447 (n_0, in[3]);
  not g448 (n_9, in[1]);
  not g446 (n_43, in[2]);
  not g445 (n_25, in[0]);
endmodule

