
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Mar  7 2020 16:40:51 EST (Mar  7 2020 21:40:51 UTC)

// Verification Directory fv/LUT_WINPUT1 

module LUT_WINPUT1(in, out, key);
  input [0:0] in;
  input [1:0] key;
  output out;
  wire [0:0] in;
  wire [1:0] key;
  wire out;
  wire n_0, n_1, n_2;
  nand g19__7837 (out, n_1, n_2);
  nand g20__7557 (n_2, key[0], n_0);
  nand g21__7654 (n_1, key[1], in);
  not g22 (n_0, in);
endmodule

