
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Mar  7 2020 16:40:47 EST (Mar  7 2020 21:40:47 UTC)

// Verification Directory fv/LUT_WINPUT3 

module LUT_WINPUT3(in, out, key);
  input [2:0] in;
  input [7:0] key;
  output out;
  wire [2:0] in;
  wire [7:0] key;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28;
  nand g195__7837 (out, n_26, n_28);
  not g196 (n_28, n_27);
  nand g197__7557 (n_27, n_24, n_25);
  nand g199__7654 (n_26, in[0], n_23);
  nand g198__8867 (n_25, n_4, n_22);
  nand g200__1377 (n_24, n_9, n_21);
  nand g201__3717 (n_23, n_17, n_19);
  nand g202__4599 (n_22, n_16, n_18);
  not g203 (n_21, n_20);
  nand g204__3779 (n_20, n_7, n_15);
  nand g205__2007 (n_19, in[1], n_14);
  nand g206__1237 (n_18, in[1], n_13);
  nand g207__1297 (n_17, in[2], n_11);
  nand g208__2006 (n_16, in[2], n_12);
  nand g209__2833 (n_15, n_0, n_5);
  nand g210__7547 (n_14, n_1, n_10);
  nand g211__7765 (n_13, n_2, n_3);
  not g212 (n_12, n_8);
  not g213 (n_11, n_6);
  nand g220__9867 (n_10, key[3], n_9);
  nand g214__3377 (n_8, key[4], n_7);
  nand g215__9719 (n_6, key[5], n_7);
  nand g216__1591 (n_5, key[0], n_4);
  nand g217__6789 (n_3, key[2], n_9);
  nand g219__5927 (n_2, key[6], in[2]);
  nand g221__2001 (n_1, key[7], in[2]);
  nand g218__1122 (n_0, key[1], in[0]);
  not g224 (n_7, in[1]);
  not g222 (n_4, in[0]);
  not g223 (n_9, in[2]);
endmodule

