
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: May  5 2020 09:31:03 EDT (May  5 2020 13:31:03 UTC)

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire n_0, n_1, n_2, n_3;
  nand g44__7837 (N22, n_0, n_3);
  nand g45__7557 (N23, n_2, n_3);
  nand g46__7654 (n_3, N2, n_1);
  nand g47__8867 (n_2, N7, n_1);
  nand g48__1377 (n_0, N3, N1);
  nand g49__3717 (n_1, N6, N3);
endmodule

