
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Mar  7 2020 16:40:48 EST (Mar  7 2020 21:40:48 UTC)

// Verification Directory fv/LUT_WINPUT2 

module LUT_WINPUT2(in, out, key);
  input [1:0] in;
  input [3:0] key;
  output out;
  wire [1:0] in;
  wire [3:0] key;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  nand g102__7837 (out, n_9, n_8);
  nand g103__7557 (n_9, n_0, n_6);
  nand g104__7654 (n_8, in[0], n_7);
  nand g105__8867 (n_7, n_2, n_4);
  nand g106__1377 (n_6, n_1, n_5);
  nand g108__3717 (n_5, key[0], n_3);
  nand g107__4599 (n_4, key[1], n_3);
  nand g109__3779 (n_2, key[3], in[1]);
  nand g110__2007 (n_1, key[2], in[1]);
  not g112 (n_3, in[1]);
  not g111 (n_0, in[0]);
endmodule

